# Generated by Django 4.2.7 on 2024-01-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zaopatrzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('ilosc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_ostatniej_kontroli', models.CharField(max_length=11)),
                ('miejsce_skladowania', models.CharField(max_length=50)),
                ('wartosc_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wartosc_brutto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena_za_szt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opis_slowny', models.CharField(max_length=50)),
            ],
        ),
    ]
