# Generated by Django 4.2.7 on 2024-01-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('stanowisko', models.CharField(max_length=50)),
            ],
        ),
    ]
