# Generated by Django 4.2.7 on 2023-12-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=100)),
                ('Nazwisko', models.CharField(max_length=100)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracownicy.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
