# Generated by Django 4.2.7 on 2023-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownicy', '0002_dane_delete_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dane',
            name='ID',
        ),
        migrations.AlterField(
            model_name='dane',
            name='Imie',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dane',
            name='Nazwisko',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
